### ISSUE TITLE
Inconsistent alignment of `CM_PARTIAL_RESOURCE_DESCRIPTOR` structure

### ISSUE THREAD

**Issue by a2x** [microsoft/wdkmetadata#65]
### Summary

The [CM_PARTIAL_RESOURCE_DESCRIPTOR](https://microsoft.github.io/windows-docs-rs/doc/windows/Wdk/System/SystemServices/struct.CM_PARTIAL_RESOURCE_DESCRIPTOR.html) structure is currently missing the `#[repr(C, packed(4))]` attribute, which is necessary to ensure 4-byte alignment on x86_64 targets. This issue leads to the [CM_PARTIAL_RESOURCE_LIST](https://microsoft.github.io/windows-docs-rs/doc/windows/Wdk/System/SystemServices/struct.CM_PARTIAL_RESOURCE_LIST.html) structure having a size of 32 bytes instead of the expected 28 bytes.

In `wdm.h` of the WDK, the definition of `CM_PARTIAL_RESOURCE_DESCRIPTOR` is currently preceded by a
```cpp
#include "pshpack4.h"
```
directive, which ensures the correct alignment.

### Crate manifest

```TOML
[dependencies.windows]
version = "0.54.0"
features = ["Wdk", "Wdk_System", "Wdk_System_SystemServices"]
```
